## ---------------------------
##
## Purpose of script: See which Bunting spectra are 'non-spectral' colors
##
## Author: Dr. Benedict Hogan, Princeton University 
##
## Date Created: 2023
##
## ---------------------------
##
## Notes: Notes: This script loads processed spectral data found in ./processed_spec.RDS
##   'processed_spec.RDS' is generated by ./BuntingDataProcessing.R. It then applies function 
##   CalcNonSpectral from ./CalcNonSpectral.R, which sees if the rank order of the stimulation
##   of each photoreceptor falls in categories defined in Stoddard et al 2020 (https://www.pnas.org/doi/full/10.1073/pnas.1919377117)
## ---------------------------

source('CalcNonSpectral.R')

##### read in processed spectra data (note, this is the output from BuntingDataProcessing.R)
temp <- readRDS('processed_spec.RDS')
specs <- temp[[1]]
spec_names <- temp[[2]]
spec_rgb <- temp[[3]]

# let's get the average spectrum per patch, per location (we're not interested in interindividual differences here)
nonsp <- specs %>%
  pivot_longer(-wl, names_to = 'spec_names') %>%
  left_join(spec_names) %>%
  group_by(wl, patch_re, location) %>%
  summarise(value = mean(value)) %>%
  pivot_wider(names_from = c(patch_re, location)) %>%
  as.rspec()

plot(nonsp)

# model the spectra into cone-catches for an average UV bird, with bluetit double-cones, (under ideal background and light)
nonsp_vis_rel <- vismodel(nonsp, 
                          visual = 'avg.uv', 
                          relative = T, 
                          trans = 'bluetit',
                          achromatic = 'bt.dc') 

# generate tetrahedral coordinates for the spectra, add our labels, and the human rgb colors
nonsp_col_rel <- colspace(nonsp_vis_rel) %>%
  select(c(u, s, m, l)) %>%
  rename(rel_VS = u,
         rel_SWS = s, 
         rel_MWS = m, 
         rel_LWS = l) %>%
  CalcNonSpectral() %>%
  select(-c(rel_VS, rel_SWS, rel_MWS, rel_LWS)) %>%
  rownames_to_column('nspec_names') %>%
  right_join(nonsp_vis_rel %>% rownames_to_column('nspec_names')) %>%
  mutate(patch_re = str_extract(nspec_names, '^.*(?=_)')) %>%
  mutate(location = str_extract(nspec_names, '(?<=_)[^:punct:]*$'))

# so are there diffs in nonspectrality across patches/locations?
nonsp_col_rel %>% 
  group_by(patch_re) %>%
  summarise(nons = sum(NonSpectral), n = n())
# Answer is no differences, but many of the colors are still non-spectral