## ---------------------------
##
## Purpose of script: Color analyses for Painted Bunting spectra
##
## Author: Dr. Benedict Hogan, Princeton University 
##
## Date Created: 2023
##
## ---------------------------
##
## Notes: This script loads processed spectral data found in ./processed_spec.RDS
##   'processed_spec.RDS' is generated by ./BuntingDataProcessing.R, and outputs plots and
##   tables to ../out/
## ---------------------------

# Lets do comparisons of color in statistical distance for dS, dL, as well as bootstrapping JND/dist to see
# if the distances are likely to be perceptible
# using https://github.com/rmaia/msdichromatism/blob/master/Rmd/lizardexample.md
# and https://academic.oup.com/beheco/article/29/3/649/4964869
# Maia & White, Comparing colors using visual models, Behavioral Ecology, Volume 29, Issue 3, May/June 2018, Pages 649–659,

# load required packages
library(pavo)
library(ggplot2)
library(broom)
library(tidyverse)
library(vegan) # for betadisper
library(gt) # for table generation

# set random seed to get repeatable results
set.seed(123) 

# convenience function to grab a distance array from a pavo coldist array
getDistMat <- function(coldist, which = 'dS'){
  out <- coldist2mat(coldist)[[which]]
  return(dist(out))
}

# convenience function to gather permanova output into one line
gatherPermaOut <- function(out, patch, distance_type = NA, weight_unweight = NA){
  pout <- tidy(out) %>% 
    pivot_wider(names_from = term, values_from = c(df, SumOfSqs, R2, statistic, p.value)) %>% 
    select(-c(statistic_Residual, statistic_Total, p.value_Residual, p.value_Total)) %>% 
    rename(statistic = `statistic_group[[x]]`) %>% 
    rename(p.value = `p.value_group[[x]]`) %>%
    mutate(patch=patch) %>%
    mutate(distance_type=distance_type) %>%
    mutate(weight_unweight = weight_unweight)
  return(pout)
}

# convenience function to collect bootcoldist output sensibly
gatherBootOut <- function(bootds, patch, weight_unweight = NA){
  bout <- bootds %>%
    as.data.frame() %>%
    rownames_to_column('contrast') %>% 
    pivot_longer(cols = -contrast, 
                 names_pattern = "(\\w+)\\.(\\w+)", names_to = c(".value", "meanupdown")) %>%
    pivot_longer(c(dS, dL)) %>% 
    pivot_wider(values_from = value, names_from = meanupdown) %>%
    rename(distance_type = name) %>%
    mutate(patch=patch) %>%
    mutate(distance_type=distance_type) %>%
    mutate(weight_unweight = weight_unweight)
  return(bout)
}

##### read in processed spectra data (note, this is the output from BuntingDataProcessing.R)
temp <- readRDS('processed_spec.RDS')
specs <- temp[[1]]
spec_names <- temp[[2]]
spec_rgb <- temp[[3]]

mergemidd <- TRUE
if(mergemidd == TRUE){
  # Merge Midd with western; Pawel considers this to be reasonable
  spec_names$spec_names <- str_replace(spec_names$spec_names, pattern = 'MIDD', replacement = 'WEST')
  spec_names$group <- str_replace(spec_names$group, pattern = 'MIDD', replacement = 'WEST')
  spec_names$location[spec_names$location == 'MIDD'] = 'WEST'
  names(specs) <- str_replace(names(specs), pattern = 'MIDD', replacement = 'WEST')
  spec_rgb$spec_names <- str_replace(spec_rgb$spec_names, pattern = 'MIDD', replacement = 'WEST')
}

##### Apply visual models

# some visual parameters for later calulating JNDs
# we can try a variety of these parameters to test for sensitivity
usen<-c(1,2,2,4) # default (Leiothrix lutea value)
useweber<-0.1 # default 0.1, 0.05 is conservative
useweber.achro<-0.1 # default is 0.1, can also try 0.18

# list patches
list_patches <- unique(spec_names$patch_re)
list_patches <- list_patches[2:length(list_patches)]
  
# grab the spectra for each patch individually 
spec_list <- list()
for(i in 1:length(list_patches)){
  which <- spec_names$patch_re == list_patches[i]
  which[1] <- TRUE
  patch_specs <- specs[,which]
  spec_list[[i]] <- patch_specs
}
spec_list <- setNames(spec_list, list_patches)

# apply visual model, here getting abs cone catches
models <- lapply(spec_list, pavo::vismodel, 
                 visual = 'avg.uv', 
                 relative = F, # this for weighted distances
                 trans = 'bluetit',
                 achromatic = 'bt.dc')

# get colorspace 
spaces <- lapply(models, colspace)

# get dS and dL - weighted color contrast and luminance contrast
deltaS <- lapply(models, coldist, achro = TRUE, n=usen, weber=useweber, weber.achro=useweber.achro, qcatch='Qi', noise = "neural")

########## Do permanovas on dS

# Setup distance matrices & groupings for each body part
distance_type <- 'dS'
mat <- lapply(deltaS, getDistMat, distance_type)
group <- lapply(mat, function(x) str_extract(rownames(as.matrix(x)), '(?<=[:punct:])[A-z]*(?=[:punct:])'))

# look at assumption of equal variances
bdisp <- lapply(names(mat), function(x) betadisper(mat[[x]], group[[x]]))
names(bdisp) <- names(mat)
lapply(bdisp, anova)

# for weighted, dS, nape has unequal variances, with west looking highest, so be careful in interpretation
TukeyHSD(bdisp$Nape)
table(group$Nape)

# Use permanova
pmanova <- lapply(names(mat), function(x) adonis2(mat[[x]] ~ group[[x]]))
names(pmanova) <- names(mat)
pmanova

# concatenate permanovas
pres <- lapply(list_patches, function(x) gatherPermaOut(pmanova[[x]], x, distance_type = 'dS', weight_unweight = 'weight'))
pres <- do.call(rbind, pres)

# so that tells us if there are -statistical- differences, but doesn't tell us if they're potentially perceptible

########## Do permanovas on dL

# Setup distance matrices & groupings for each body part
distance_type <- 'dL'
mat <- lapply(deltaS, getDistMat, distance_type)
group <- lapply(mat, function(x) str_extract(rownames(as.matrix(x)), '(?<=[:punct:])[A-z]*(?=[:punct:])'))

# look at assumption of equal variances
bdisp <- lapply(names(mat), function(x) betadisper(mat[[x]], group[[x]]))
names(bdisp) <- names(mat)
lapply(bdisp, anova)

# for weighted, dL also, nape has unequal variances, so be careful in interpretation
TukeyHSD(bdisp$Nape)
table(group$Nape)

# Use permanova
pmanova_l <- lapply(names(mat), function(x) adonis2(mat[[x]] ~ group[[x]]))
names(pmanova_l) <- names(mat)
pmanova_l

# concatenate permanovas
pres_l <- lapply(list_patches, function(x) gatherPermaOut(pmanova_l[[x]], x, distance_type = 'dL', weight_unweight = 'weight'))
pres_l <- do.call(rbind, pres_l)

## so full permanova table (chromatic and achromatic)

perm_comp <- rbind(pres, pres_l)

# generate a nice table of these results
ptab <- perm_comp %>%
  rename(df = `df_group[[x]]`) %>% 
  select(distance_type, patch, statistic, df, p.value) %>%
  pivot_longer(-c(distance_type, patch)) %>% 
  pivot_wider(names_from = c(patch, name)) %>% 
  rename(Contrast = distance_type) %>%
  gt() |>
  tab_spanner(
    label = "Upper breast",
    columns = starts_with('Upper')
  )|>
  tab_spanner(
    label = "Belly",
    columns = starts_with('Belly')
  )|>
  tab_spanner(
    label = "Rump",
    columns = starts_with('Rump')
  )|>
  tab_spanner(
    label = "Coverts",
    columns = starts_with('Coverts')
  )|>
  tab_spanner(
    label = "Mantle",
    columns = starts_with('Mantle')
  )|>
  tab_spanner(
    label = "Nape",
    columns = starts_with('Nape')
  ) |>
  cols_label(
    ends_with("df") ~ "df",
    ends_with("statistic") ~ "F",
    ends_with("value") ~ "p"
  ) |>
  fmt_number(
    columns = contains('p.value'),
    decimals = 3,
    use_seps = FALSE
  )|>
  fmt_number(
    columns = contains('statistic'),
    decimals = 2,
    use_seps = FALSE
  )
ptab

gtsave(ptab, paste0('../out/ptable', '_weber', useweber, '_aweber', useweber.achro, '_n', paste0(usen, collapse = ''), '_nomidd.docx'))
# gtsave(ptab, '../out/ptable.png')

########## See if perceptual differences are large
# get groups for each model
groups <- lapply(models, function(x) str_extract(rownames(x), '(?<=[:punct:])[A-z]*(?=[:punct:])'))

# get bootstrapped color contrast per group
bootds <- lapply(list_patches, function(x) bootcoldist(models[[x]], groups[[x]], boot.n = 3000, n=usen, weber=useweber, weber.achro=useweber.achro, qcatch='Qi', noise = "neural"))
bootds <- setNames(bootds, list_patches)

# concatenate those results
bootres <- lapply(list_patches, function(x) gatherBootOut(bootds[[x]], x, 'weight'))
bootres <- do.call(rbind, bootres)

# example plot of those results
models$Belly %>% 
  rownames_to_column('spec_names') %>% 
  mutate(group = str_extract(spec_names, '(?<=[:punct:])[A-z]*(?=[:punct:])')) %>% 
  ggplot(aes(x = group, y = lum, color = group, group = group)) + 
  geom_violin() + 
  geom_point()

sigs <- perm_comp %>%
  rename(df = `df_group[[x]]`) %>% 
  select(distance_type, patch, statistic, df, p.value) %>%
  pivot_longer(-c(distance_type, patch)) %>%
  filter(name == 'p.value') %>%
  mutate(highlight = value < .05)

# could plot those bootstrapped color distances between groups

if(length(unique(bootres$contrast)) > 1){ # if greater than one contrast, enpanel as original, othwerwise simplify
  plo <- bootres %>%
    left_join(sigs) %>%
    mutate(contrast = str_replace(contrast, 'EAST', 'East')) %>%
    mutate(contrast = str_replace(contrast, 'WEST', 'Southwest')) %>%
    mutate(contrast = str_replace(contrast, 'MIDD', 'Central')) %>%
    mutate(contrast = factor(contrast, levels = c('East-Central', 'East-Southwest', 'Central-Southwest'))) %>%
    mutate(patch = factor(patch, levels = c('Upper breast', 'Belly', 'Rump', 'Coverts', 'Mantle', 'Nape'))) %>%
    mutate(distance_type = factor(distance_type, levels = c('dS', 'dL'))) %>%
    ggplot(aes(x = contrast, y = mean)) +
    geom_point(aes(fill = highlight, color = highlight), show.legend = F, size = 3, colour="black", pch=21) +
    geom_errorbar(aes(ymin = lwr, ymax = upr, width = 0), show.legend = F) +
    ylim(c(0,3)) +
    facet_grid(rows = vars(distance_type), cols = vars(patch)) + # had depreciated switch = "y"
    ylab('Color (dS) and brightness (dL) contrast') + xlab('Group comparison') +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 12),
          panel.border = element_rect(colour = "black", fill=NA), 
          panel.background = element_blank(),
          axis.title.x = element_blank()) +
    geom_hline(yintercept = 1, linetype = 'dashed', alpha = 0.5)
  
  pw <- 8
  ph <- 4
    
} else {
plo <- bootres %>%
  left_join(sigs) %>%
  mutate(contrast = str_replace(contrast, 'EAST', 'East')) %>%
  mutate(contrast = str_replace(contrast, 'WEST', 'Southwest')) %>%
  mutate(contrast = str_replace(contrast, 'MIDD', 'Central')) %>%
  mutate(contrast = factor(contrast, levels = c('East-Central', 'East-Southwest', 'Central-Southwest'))) %>%
  mutate(patch = factor(patch, levels = c('Upper breast', 'Belly', 'Rump', 'Coverts', 'Mantle', 'Nape'))) %>%
  mutate(distance_type = factor(distance_type, levels = c('dS', 'dL'))) %>%
  ggplot(aes(x = patch, y = mean)) +
  geom_point(aes(fill = highlight, color = highlight), show.legend = F, size = 3, colour="black", pch=21) +
  geom_errorbar(aes(ymin = lwr, ymax = upr, width = 0), show.legend = F) +
  ylim(c(0,3)) +
  facet_wrap(vars(distance_type), nrow = 2) + # had depreciated switch = "y"
  ylab('Color (dS) and brightness (dL) contrast') + xlab('Group comparison') +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 12),
        panel.border = element_rect(colour = "black", fill=NA), 
        panel.background = element_blank(),
        axis.title.x = element_blank()) +
  geom_hline(yintercept = 1, linetype = 'dashed', alpha = 0.5)

  pw <- 4
  ph <- 4
}

ggsave(paste0('../out/weighted_color_contrasts', '_weber', useweber, '_aweber', useweber.achro, '_n', paste0(usen, collapse = ''), '_nomidd.png'), plot = plo, width = pw, height = ph, scale = 1.1)
# So, for weighted color (dS) contrast, we're
# thinking that those nape results don't confer percepually different color
# only reflects different variance between groups. 

# tidy up a bit
rm(plo)
rm(ptab)